import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HelloWorld from './components/HelloWorld'

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
               
            </Head>
            <div>
                <HelloWorld name="Next Js"/>
            </div>
        </div>
    )
}
